version: '3'
services:
  redis-node1:
    image: redis:latest
    command: ["--cluster-enabled", "yes", "--cluster-config-file", "nodes-node-1.conf", "--port", "6379"]
    volumes:
      - /data/redis-data/node1:/data
    network_mode: "host"
  redis-node2:
    image: redis:latest
    command: ["--cluster-enabled", "yes", "--cluster-config-file", "nodes-node-2.conf", "--port", "6380"]
    volumes:
      - /data/redis-data/node2:/data
    network_mode: "host"
  redis-node3:
    image: redis:latest
    command: ["--cluster-enabled", "yes", "--cluster-config-file", "nodes-node-3.conf", "--port", "6381"]
    volumes:
      - /data/redis-data/node3:/data
    network_mode: "host"
  redis-node4:
    image: redis:latest
    command: ["--cluster-enabled", "yes", "--cluster-config-file", "nodes-node-4.conf", "--port", "6382"]
    volumes:
      - /data/redis-data/node4:/data
    network_mode: "host"
  redis-node5:
    image: redis:latest
    command: ["--cluster-enabled", "yes", "--cluster-config-file", "nodes-node-5.conf", "--port", "6383"]
    volumes:
      - /data/redis-data/node5:/data
    network_mode: "host"
  redis-node6:
    image: redis:latest
    command: ["--cluster-enabled", "yes", "--cluster-config-file", "nodes-node-6.conf", "--port", "6384"]
    volumes:
      - /data/redis-data/node6:/data
    network_mode: "host"
